name: tfinx
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.3
  # # # - matplotlib=3.3.3
  # # # - matplotlib-venn=0.11.6
  - openpyxl=3.0.9
  - ipykernel=6.4.2
  - altair=4.1.0
  - altair_saver=0.4.0
  - biopython=1.79
  - click=8.0.3
  - jupyterlab=3.2.1
  - numpy=1.21.2
  - pandas=1.3.2
  - pybedtools=0.8.2
  - pyliftover=0.4
  - pyjaspar=2.1.0
  #FOR TADBIT
  - imp=2.14.0
  - mcl=14.137
  - tadbit=1.0.1
